### ISSUE TITLE
code: 404, message: 'Not Found'

### ISSUE THREAD

**Issue by tiny-tinker** [extrabacon/google-oauth-jwt#8]
Hello!
   I am attempting to use this module to pull back calendar events. I can successfully pull back events using the calendar.events.list at [API Explorer](https://developers.google.com/apis-explorer/#p/calendar/v3/calendar.events.list) by entering my gmail address as the calendarId. Sweet. So, now, I am trying to pull those events from code with this module. 
This is the result of running the node console:

```
> var request = require('google-oauth-jwt').requestWithJWT();
undefined
> var inspect = require('util').inspect;
undefined
>
undefined
> request({
...   url: 'https://www.googleapis.com/calendar/v3/calendars/email%40gmail.com/events',
...   jwt: {
.....     // use the email address of the service account, as seen in the API console
.....     email: 'lotsonumbersbehere@developer.gserviceaccount.com',
.....     // use the PEM file we generated from the downloaded key
.....     keyFile: './googleapi-privatekey.pem',
.....     // specify the scopes you wish to access - each application has different scopes
.....     scopes: ['https://www.googleapis.com/auth/calendar']
.....   }
... }, function (err, res, body) {
...     console.log(JSON.parse(body));
...
... });
undefined
> { error: { errors: [ [Object] ], code: 404, message: 'Not Found' } }

```

I was successful in pulling the events down using a REST project in SOAPUI by copying the bearer authorization token from the API Explorer and the endpoint and resource were the same as that url string above. 

Any ideas?

**Comment by Emerald214** [comment]
@nomadic-squirrel Thank you for the idea that shares the calendar with the email which is registered in Service Account. I have the same problem and it has been solved.

I followed the tutorial until here https://developers.google.com/accounts/docs/OAuth2ServiceAccount#delegatingauthority

but I don't understand what it means because I don't see any link "Security " or "More controls". I'm not sure if your solution is related to "delegating authority".
